# Makefile for ImageInfo
# Copyright: Robert Sprowson 2023, distributed under CDDL v1.1 
# SPDX-License-Identifier: CDDL-1.1
#

COMPONENT = ImageInfo
OBJS      = info sprite jpeg

include CApp

# Dynamic dependencies:
